
#' Readings Dataset
#'
#' Dataset containing relative humidity, barometric pressure, ambient
#' temperature and other data obtained from a BME280 sensor connected to a
#' Raspberry Pi.
#'
#' The data frame includes the following variables:
#'
#' \describe{
#'
#' \item{\code{reading_id}}{Unique character string generated by the BME280 sensor
#' for a reading.}
#'
#' \item{\code{date_time}}{The date and time of a sensor reading.}
#'
#' \item{\code{interval}}{The time difference between a sensor reading and the
#' prior sensor reading, expressed in minutes.  Note that sensor
#' readings were taken initially at five-minute intervals, then increased to
#' one-minute intervals.  Extremely high humidity levels occasionally caused the
#' sensor to stop functioning, requiring a reboot of the Raspberry Pi.  These
#' breaks in readings are reflected in some non-standard intervals.}
#'
#' \item{\code{degrees_celcius}}{The ambient temperature expressed on the Celcius
#' scale.}
#'
#' \item{\code{degrees_fahrenheit}}{The ambient temperature expressed on the
#' Fahrenheit scale.}
#'
#' \item{\code{barometric_pressure}}{The atmospheric pressure expressed in
#' hectopascal units (hPa).}
#'
#' \item{\code{relative_humidity}}{The concentration of water vapor in the air
#' expressed as a percentage, indicating the present state of absolute humidity
#' relative to a maximum humidity given the same temperature.}
#'
#' \item{\code{state}}{Categorical variable; identifies the
#' state and location of a dehumidifier with three possible values: N indicates
#' dehumidifier is not running, D (direct) indicates dehumidifier is running and present
#' in the same room as the BME280 sensor and I (indirect) indicates the dehumidifier is
#' running and present in a room adjacent to the BME280 sensor.}
#'
#' \item{\code{room}}{Categorical variable; identifies the location
#' of the sensor with two possible values: UB indicates the sensor location is in
#' the second floor bathroom and UH indicates the sensor is in the second floor
#' hallway.}
#'
#' \item{\code{peak_rh}}{Boolean value; indicates whether a reading is considered
#' a peak relative humidity value.  For details on how peak values are determined,
#' refer to the documentation for the \code{find_peaks} function.}
#' }
#'
#' @docType data
#'
#' @keywords dataset
#'
#' @name readings
#'
#' @usage data(readings)
#'
#' @format A data frame with observations captured at regular intervals of time
#' and ten variables.
#'
#' @author Donnie Minnick \email{donnie.minnick@gmail.com}
#'

"readings"
